# Generated by Django 5.1 on 2024-09-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
    ]
